### ISSUE TITLE
Multiple Refresh - Random behaviour

### ISSUE THREAD

**Issue by thehogg13** [bendigoadelaide/tssupport-issues#1]
After signing in, if you refresh the page , it appears you are logged out. Then if you refresh again , it refreshes and realises you are actually authenticated and shows the menus.

Also , sometimes after first sign on, the contacts button doesnt display the contacts , you have to do the above refresh process (of 2 refreshes) and then you can view the contacts.

Happens on Android, Chrome and IOS devices.

**Comment by JProgrammer** [comment]
Fixed will reinitialize menu on login
