### ISSUE TITLE
Hidden when a member of more than 1 group

### ISSUE THREAD

**Issue by thehogg13** [bendigoadelaide/tssupport-issues#4]
If a contact, that 'Is Bank staff' and is a member of 2 departments , their contact card doesnt not appear under either of the Departments. Example Jason Tusa is a member of both Identity Management and Middleware , and when both groups are selected he appears under neither group. Jason is now just under Middleware so he appears.

**Comment by JProgrammer** [comment]
Changed the query this is now fixed
